spring:
  application:
    name: loan-approval-poc
  datasource:
    app:
      url: jdbc:h2:mem:app-db;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:
      hikari:
        maximum-pool-size: 10
    camunda:
      url: jdbc:h2:mem:camunda-db;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:
      hikari:
        maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

camunda:
  bpm:
    enabled: true
    database:
      type: h2
      schema-update: drop-create


      # Job executor configuration
    job-execution:
      enabled: true  # Enable job executor (runs async tasks like timers, messages)
      core-pool-size: 5
      max-pool-size: 20
      queue-capacity: 30

    # Deployment settings
    deployment-resource-pattern: "bpmn/LOAN_APPROVAL_PROCESS_CAMUNDA.bpmn"  # Location of BPMN files
    auto-deployment-enabled: true  # Auto deployment of BPMN processes

    # Webapp configuration
    webapp:
      enabled: true  # Enable Camunda web apps (Cockpit, Tasklist, Admin)
      index-redirect-enabled: true  # Redirect to the Camunda webapp at root path

    # REST API
    rest:
      enabled: true  # Enable the Camunda REST API
