spring:
  application:
    name: loan-approval-poc
  datasource:
    app:
      url: jdbc:h2:mem:app-db;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:
      hikari:
        maximum-pool-size: 10
    camunda:
      url: jdbc:h2:mem:camunda-db;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:
      hikari:
        maximum-pool-size: 10

camunda:
  bpm:
    enabled: true
    database:
      schema-update: true
      driver: org.h2.Driver
      url: jdbc:h2:mem:camunda-db;DB_CLOSE_DELAY=-1
      username: sa
      password:
    auto-deployment-enabled: true
