server:
  port: 9090
spring:
  application:
    name: loan-approval-poc
  datasource:
    app:
      url: jdbc:h2:mem:app-db;DB_CLOSE_DELAY=-1;
      driver-class-name: org.h2.Driver
      username: sa
      password:
      hikari:
        maximum-pool-size: 10
    camunda:
      url: jdbc:h2:mem:camunda-db;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:
      hikari:
        maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

zeebe:
  client:
    security:
      plaintext: true
    broker:
      grpcAddress: http://127.0.0.1:26500
      restAddress: http://127.0.0.1:8080




camunda:
  client:
    tasklist:
      base-url: http://127:0:0:1:8080
      enabled: true
    operate:
      audience: operate-api
      base-url: http://127:0:0:1:8080
      enabled: true
    auth:
      password: demo
      username: demo
    mode: selfManaged
    zeebe:
      prefer-rest-over-grpc=false:
      base-url: http://127:0:0:1:8080
      gateway-url: http://127:0:0:1:26500
      preferRestOverGrpc: true








