spring:
  application:
    name: loan-approval-poc
  datasource:
    url: jdbc:h2:file:./Camunda-POC-App_DB_1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: APPPOC
    password: APPPOC
    driver:
      class: org.h2.Driver
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console