server:
  port: 9090
spring:
  application:
    name: loan-approval-poc
  datasource:
    app:
      url: jdbc:h2:mem:app-db;DB_CLOSE_DELAY=-1;
      driver-class-name: org.h2.Driver
      username: sa
      password:
      hikari:
        maximum-pool-size: 10
    camunda:
      url: jdbc:h2:mem:camunda-db;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:
      hikari:
        maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      firstName: Demo
    filter:
      create: All tasks
    client:
      base-url: http://localhost:9090/engine-rest
      subscriptions:
        externalServiceTask:
          variable-names: [loan-id]
          process-definition-key: LOAN_APPROVAL_PROCESS






